spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authdb
    username: root
    password: shadan@07

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: mySuperSecretKeyForJwtThatIsLongEnough12345
  expiration: 3600000

