spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productdb
    username: root
    password: shadan@07   # change if your password different

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
